name: ZERGHQ
favicon: null
layout_spectrum: 0.17069
typography_spectrum: 0.54692
title: Zerg HQ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feefdc'
    - '#c0b2a7'
    - '#1b1110'
    - '#43322a'
    - '#8a7059'
  brandStrength: 0.3507695428561419
  lightness: 0.6316717027220875
  saturation: 0.5688314130529761
  rhythmicContrast: 0.17169356578961015
purpose: []
